### ISSUE TITLE
App crashes on closing child window when using window_manager (windows 10)

### ISSUE THREAD

**Issue by CroatianHusky** [MixinNetwork/flutter-plugins#169]
Whenever I try to use the `window_manager` package, the app crashes as soon as I try to interact with the main window after closing a child window. Both in debug and release mode.

I'm using Flutter 3.3.8 stable.

I attached the minimal code to reproduce:
[window_manager_crash.zip](https://github.com/MixinNetwork/flutter-plugins/files/10107756/window_manager_crash.zip)

**Comment by damywise** [comment]
Maybe take a look at https://github.com/Kingtous/rustdesk_desktop_multi_window

**Comment by CroatianHusky** [comment]
I just tried it with my attached example, and it crashed exactly the same.

**Comment by damywise** [comment]
not sure what you mean by tried it, maybe look at the example and see how they used it

**Comment by CroatianHusky** [comment]
Both the desktop_multi_window and rustsesk_desktop_multi_window plugins' examples crash after I click on the create a new world button

**Comment by damywise** [comment]
weird, mine works perfectly

**Comment by CroatianHusky** [comment]
I'll have to try it on another system or a VM then, but I can't do that until probably a few weeks.

**Comment by damywise** [comment]
Flutter 3.3.9

**Comment by SiongSng** [comment]
I successfully reproduced this problem using Flutter 3.7.0-1.1.pre (beta) test
OS: Windows 11

**Comment by SiongSng** [comment]
But if you don't use the `window_manager` package to close the window, it can work normally

**Comment by rashcroft7** [comment]
I am having the same issue as @CroatianHusky. Do we need to do any plugin cleanup in FlutterWindow::OnDestroy?

Flutter 3.7.0-19.0.pre, on Microsoft Windows [Version 10.0.19045.2486]

**Comment by jijibong** [comment]
> I am having the same issue as @CroatianHusky. Do we need to do any plugin cleanup in FlutterWindow::OnDestroy?
> 
> Flutter 3.7.0-19.0.pre, on Microsoft Windows [Version 10.0.19045.2486]

you can close child window by windowManager.destroy()

**Comment by annd22** [comment]
I used the windowManager.destroy() to close the sub window, but it still make the main window crash, so now I currently just hide the sub window, not close it, everything goes on.

**Comment by rashcroft7** [comment]
For those still having trouble, I am no longer getting errors using [rustdesk_window_manager](https://github.com/Kingtous/rustdesk_window_manager) with [rustdesk_desktop_multi_window](https://github.com/Kingtous/rustdesk_desktop_multi_window)

```
  window_manager:
        git:
            url: https://github.com/Kingtous/rustdesk_window_manager
            ref: 32b24c66151b72bba033ef8b954486aa9351d97b

  desktop_multi_window:
    git:
        url: https://github.com/Kingtous/rustdesk_desktop_multi_window
        ref: bc8604a88e52b2b6e64d2661ae49a71450a47af8

```
