### ISSUE TITLE
broken on WASM Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by sgehrman** [MixinNetwork/flutter-plugins#397]
_handleMethodChannel: Unsupported operation: Platform._operatingSystem     at http://localhost:8765/main.dart.wasm:wasm-function[1209]:0x50e5ea

**Comment by sgehrman** [comment]
see PR for fix

**Comment by trunghieuvn** [comment]
I happend same as this issue
```
main.dart.wasm:wasm-function[18155]:0x2d290e
main.dart.mjs:60 _handleMethodChannel: Unsupported operation: Platform._operatingSystem     at main.dart.wasm:wasm-function[1062]:0x143340
```

**Comment by trunghieuvn** [comment]
I has ready fixed in my branch, PLEASE link my PR: https://github.com/MixinNetwork/flutter-plugins/pull/399

```
desktop_drop: #^0.5.0
    git:
      url: https://github.com/fighttech-vn/flutter-plugins/
      path: packages/desktop_drop
      ref: 4eaaa5e
```
